### ISSUE TITLE
Open-Source Checklist

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/annon.api#106]
# General
- [x] Refactor tests (more acceptance testing, stable test result, fully functional smoke test)
- [x] Write docs (setup with docker, without it, in kubernetes, available environment variables)
- [x] Write `@doc` in most important methods, expand `@moduledoc`'s to match full module responsibility
- [ ] Get rid from PostgreSQL in requests log (and probably from configs), we need low-write-latency DB, like Cassandra.
- [x] Rename private api to management api.
- [x] Coverage > 90%
- [x] Clean all TODO's from code
- [x] Allow to update settings (`PUT` request) partially without need to pass full objects.
- [x] Deal with duplicate `//` in path and relative URIs in config resolving and proxy.
- [x] Add tests for consumer plugins overrides (acceptance on each plugin)
- [x] Rename `ip_blacklist` and `ip_whitelist` settings to `blacklist` and `whitelist`.
- [x] Smarter check for duplicate APIs (methods can override each other)
- [x] Rename everything to Annon.
- [x] Review API doc and refactor code to match latest API manifest.

# Proxy
- [x] Support `X-Host-Override` header
- [x] Add "hide credentials" in proxy settings to hide `Authorization` header. But proxy rest of headers
- [x] Allow wildcard `*.example.com` domain names
- [x] Add `strip_request_path` option that should tell if we should strip API-related path from upstream request URI
- [x] Add `strip_request_host` and proxy `HOST` header by default
- [x] Rename `strip_request_path` to `strip_api_path`
- [ ] Test cookie support
- [x] Send `X-Forwarded-Proto` header (http or https)
- [ ] Add `connection_timeout`, `receive_timeout` settings
- [ ] Add `retries_limit` and set it to 0 by default.

# Auth
- [x] Add Basic authorization strategy with sample auth server (as separate project that is called via RPC/REST)
- [x] Set additional headers when proxying authorized requests: `X-Consumer-External-ID`, `X-Consumer-Scopes`, `X-Forwarded-For`
- [ ] ~~ Add api key authorization strategy ~~

# Security
- [x] CORS plugin
- [x] SSL native support (and investigate slow SSL implementation in Erlang)
- [ ] Rate Limiting plugin
- [ ] Size limiting plugin (Cowboy does not allow to stop request before it fully received, need some kind of hack around it)
- [x] Provide a way to hide secrets from logs (user passwords, tokens, etc)
- [ ] Add token-based auth for private API

# GUI
- [x] Beta version for management GUI

# Perfomance
- [ ] Stress tests, describe limitations, clustering strategies
- [ ] Optimize places where we work with DB (not cache) - Logger, Consumers.
- [x] Speed up config resolving

# Nice to have
- [X] ~Cache plugin and hex package to read from it via RPC~
- [x] Auto-generated status pages
- [ ] Binary protocol parser
